/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bDfgY6l02Ro
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export function WeatherReport() {
  return (
    <div className="flex flex-wrap justify-center items-center gap-8 p-8">
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>New York</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col items-center gap-4">
          <CloudIcon className="w-16 h-16 text-gray-500" />
          <div className="text-4xl font-bold">15°C</div>
          <div className="text-gray-500">Humidity: 60%</div>
          <div className="text-gray-500">Cloudy</div>
        </CardContent>
      </Card>
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>London</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col items-center gap-4">
          <SunIcon className="w-16 h-16 text-yellow-500" />
          <div className="text-4xl font-bold">20°C</div>
          <div className="text-gray-500">Humidity: 50%</div>
          <div className="text-gray-500">Sunny</div>
        </CardContent>
      </Card>
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>Tokyo</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col items-center gap-4">
          <CloudRainIcon className="w-16 h-16 text-blue-500" />
          <div className="text-4xl font-bold">18°C</div>
          <div className="text-gray-500">Humidity: 70%</div>
          <div className="text-gray-500">Rainy</div>
        </CardContent>
      </Card>
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>Paris</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col items-center gap-4">
          <CloudIcon className="w-16 h-16 text-gray-500" />
          <div className="text-4xl font-bold">17°C</div>
          <div className="text-gray-500">Humidity: 65%</div>
          <div className="text-gray-500">Cloudy</div>
        </CardContent>
      </Card>
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>Sydney</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col items-center gap-4">
          <SunIcon className="w-16 h-16 text-yellow-500" />
          <div className="text-4xl font-bold">25°C</div>
          <div className="text-gray-500">Humidity: 40%</div>
          <div className="text-gray-500">Sunny</div>
        </CardContent>
      </Card>
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>Moscow</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col items-center gap-4">
          <CloudSnowIcon className="w-16 h-16 text-blue-300" />
          <div className="text-4xl font-bold">-5°C</div>
          <div className="text-gray-500">Humidity: 80%</div>
          <div className="text-gray-500">Snowy</div>
        </CardContent>
      </Card>
    </div>
  )
}


function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 6.71-9h1.79a4.5 4.5 9Z" />
    </svg>
  )
}


function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41" />
      <path d="m17.66 17.66 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}


function CloudRainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 14.899A7 7 0 1 15.71 8h1.79a4.5 4.5 2.5 8.242" />
      <path d="M16 14v6" />
      <path d="M8 14v6" />
      <path d="M12 16v6" />
    </svg>
  )
}


function CloudSnowIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 14.899A7 7 0 1 15.71 8h1.79a4.5 4.5 2.5 8.242" />
      <path d="M8 15h.01" />
      <path d="M8 19h.01" />
      <path d="M12 17h.01" />
      <path d="M12 21h.01" />
      <path d="M16 15h.01" />
      <path d="M16 19h.01" />
    </svg>
  )
}
